repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.0.0
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==20.8b1]
   - id: nbqa-isort
     additional_dependencies: [isort==5.6.4]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      args: [--line-length, "99"]


- repo: https://github.com/PyCQA/isort
  rev: 5.8.0
  hooks:
    - id: isort
      args: [--profile, black, --filter-files]

