# @package _global_

# specify here default preprocessing configuration
defaults:
    # can be any config file in the preprocessing_pipeline folder
    - preprocessing_pipeline: decision_tree.yaml 
    
    
# You might add another configurations: which model to use, which visualizations, etc. 